//! Implements A2 (Events and Traces) and A4 (Time and Causality).
//!
//! Formal objects: events `e = (id, ts, actor, action, target)`, traces as
//! totally ordered sequences of events, the causality relation generated by
//! actor identity and target handoff, vector clocks realising A4's partial
//! order, and regular patterns over the action alphabet.
//!
//! In a SIEM/XDR pipeline this crate holds the reconstructed activity record:
//! the sensor appends events, detection rules match action patterns anchored to
//! whole traces, and vector clocks expose concurrency so causally unrelated
//! alerts are not stitched into a single attack narrative.
#![forbid(unsafe_code)]

use std::collections::{BTreeMap, BTreeSet};

/// Stable handle for an event within a trace.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct EventId(pub u64);

/// One A2 event; `target` is the entity acted upon, if any.
#[derive(Debug, Clone, PartialEq)]
pub struct TraceEvent {
    /// Stable identity, used as the tie-break for equal timestamps.
    pub id: EventId,
    /// Wall-clock timestamp in nanoseconds since the epoch.
    pub ts_ns: i64,
    /// Acting entity id.
    pub actor: u64,
    /// Action verb, e.g. `create_process` or `set_value`.
    pub action: Box<str>,
    /// Entity acted upon, if the action had a target.
    pub target: Option<u64>,
}

/// An indexed sequence of events, retained in arrival order.
#[derive(Debug, Clone)]
pub struct Trace {
    events: Vec<TraceEvent>,
}

impl Trace {
    /// Creates an empty trace.
    pub fn new() -> Self {
        Self { events: Vec::new() }
    }

    /// Appends an event; arrival order is preserved and `in_time_order` sorts.
    pub fn push(&mut self, e: TraceEvent) {
        self.events.push(e);
    }

    /// Number of events in the trace.
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// True when the trace has no events.
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Action verbs in arrival order.
    pub fn actions(&self) -> Vec<&str> {
        self.events.iter().map(|e| e.action.as_ref()).collect()
    }

    /// Events sorted by `(ts_ns, id)`; the id tie-break keeps this total.
    pub fn in_time_order(&self) -> Vec<&TraceEvent> {
        let mut out: Vec<&TraceEvent> = self.events.iter().collect();
        out.sort_by_key(|e| (e.ts_ns, e.id.0));
        out
    }

    /// A4 causality: true when the events share an actor, or when `a` acted on
    /// the entity that `b` acts as. The relation is directed.
    pub fn causally_linked(a: &TraceEvent, b: &TraceEvent) -> bool {
        a.actor == b.actor || a.target == Some(b.actor)
    }
}

impl Default for Trace {
    fn default() -> Self {
        Self::new()
    }
}

/// A vector clock over actor ids: the A4 happens-before partial order.
#[derive(Debug, Clone, PartialEq)]
pub struct VectorClock {
    map: BTreeMap<u32, u64>,
}

impl VectorClock {
    /// Creates a clock with no ticks.
    pub fn new() -> Self {
        Self {
            map: BTreeMap::new(),
        }
    }

    /// Advances `actor`'s component and returns its new value.
    pub fn tick(&mut self, actor: u32) -> u64 {
        let slot = self.map.entry(actor).or_insert(0);
        *slot += 1;
        *slot
    }

    /// Reads a component; absent actors read as zero.
    pub fn get(&self, actor: u32) -> u64 {
        self.map.get(&actor).copied().unwrap_or(0)
    }

    /// Componentwise maximum in place.
    pub fn merge(&mut self, other: &VectorClock) {
        for (&actor, &v) in &other.map {
            let slot = self.map.entry(actor).or_insert(0);
            *slot = (*slot).max(v);
        }
    }

    /// Componentwise `<=` over the union of components (absent means zero).
    fn le(&self, other: &VectorClock) -> bool {
        self.map
            .keys()
            .chain(other.map.keys())
            .all(|k| self.get(*k) <= other.get(*k))
    }

    /// Strict A4 precedence: `self <= other` and the clocks differ.
    pub fn happens_before(&self, other: &VectorClock) -> bool {
        self.le(other) && self.map != other.map
    }

    /// True when neither clock precedes the other; identical clocks are equal,
    /// not concurrent.
    pub fn concurrent(&self, other: &VectorClock) -> bool {
        !self.le(other) && !other.le(self)
    }
}

impl Default for VectorClock {
    fn default() -> Self {
        Self::new()
    }
}

/// A regular expression over the action alphabet, matched against whole words.
#[derive(Debug, Clone, PartialEq)]
pub enum Pattern {
    /// Matches exactly one specific action.
    Atom(Box<str>),
    /// Matches any single action.
    Any,
    /// Concatenation, left to right.
    Seq(Vec<Pattern>),
    /// Alternation; any branch may match.
    Alt(Vec<Pattern>),
    /// Kleene star: zero or more repetitions of the inner pattern.
    Star(Box<Pattern>),
}

impl Pattern {
    /// Anchored full match: the pattern must consume the entire word.
    pub fn matches(&self, word: &[&str]) -> bool {
        self.ends(word, 0).contains(&word.len())
    }

    /// Every position reachable after matching `self` from `pos`. Working in
    /// position sets (rather than booleans) is what lets `Star` backtrack.
    fn ends(&self, w: &[&str], pos: usize) -> BTreeSet<usize> {
        let mut out = BTreeSet::new();
        match self {
            Pattern::Atom(a) => {
                if pos < w.len() && w[pos] == &**a {
                    out.insert(pos + 1);
                }
            }
            Pattern::Any => {
                if pos < w.len() {
                    out.insert(pos + 1);
                }
            }
            Pattern::Seq(ps) => {
                let mut cur = BTreeSet::from([pos]);
                for p in ps {
                    let mut next = BTreeSet::new();
                    for c in &cur {
                        next.extend(p.ends(w, *c));
                    }
                    cur = next;
                    if cur.is_empty() {
                        break;
                    }
                }
                out = cur;
            }
            Pattern::Alt(ps) => {
                for p in ps {
                    out.extend(p.ends(w, pos));
                }
            }
            Pattern::Star(inner) => {
                out.insert(pos);
                let mut frontier = inner.ends(w, pos);
                while let Some(&c) = frontier.iter().next() {
                    frontier.remove(&c);
                    // Only newly reachable positions are expanded, which
                    // terminates even for inner patterns that match empty.
                    if out.insert(c) {
                        frontier.extend(inner.ends(w, c));
                    }
                }
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ev(id: u64, ts: i64, actor: u64, action: &str, target: Option<u64>) -> TraceEvent {
        TraceEvent {
            id: EventId(id),
            ts_ns: ts,
            actor,
            action: action.into(),
            target,
        }
    }

    #[test]
    fn trace_preserves_arrival_and_orders_by_time_then_id() {
        let mut t = Trace::new();
        assert!(t.is_empty());
        t.push(ev(2, 200, 1, "write_file", Some(9)));
        t.push(ev(1, 100, 1, "create_process", None));
        t.push(ev(3, 200, 2, "open_key", Some(9)));
        assert_eq!(t.len(), 3);
        assert_eq!(
            t.actions(),
            vec!["write_file", "create_process", "open_key"]
        );
        let ordered: Vec<u64> = t.in_time_order().iter().map(|e| e.id.0).collect();
        assert_eq!(ordered, vec![1, 2, 3]);
    }

    #[test]
    fn causal_link_follows_actor_and_target_handoff() {
        let a = ev(1, 10, 7, "spawn", Some(8));
        let b = ev(2, 20, 8, "connect", None);
        let c = ev(3, 30, 9, "read", None);
        assert!(Trace::causally_linked(&a, &b));
        assert!(Trace::causally_linked(&a, &ev(4, 40, 7, "idle", None)));
        assert!(!Trace::causally_linked(&a, &c));
        assert!(!Trace::causally_linked(&b, &a));
    }

    #[test]
    fn vector_clock_ticks_and_reads_absent_actors_as_zero() {
        let mut vc = VectorClock::new();
        assert_eq!(vc.get(1), 0);
        assert_eq!(vc.tick(1), 1);
        assert_eq!(vc.tick(1), 2);
        assert_eq!(vc.tick(2), 1);
        assert_eq!(vc.get(1), 2);
        assert_eq!(vc.get(2), 1);
    }

    #[test]
    fn happens_before_is_strict_merge_is_componentwise_max() {
        let mut a = VectorClock::new();
        a.tick(1);
        let mut b = a.clone();
        b.tick(2);
        assert!(a.happens_before(&b));
        assert!(!b.happens_before(&a));
        assert!(!a.happens_before(&a.clone()));

        let mut c = VectorClock::new();
        c.tick(3);
        assert!(a.concurrent(&c));
        assert!(!a.concurrent(&a.clone()));

        let mut m = a.clone();
        m.merge(&c);
        assert_eq!(m.get(1), 1);
        assert_eq!(m.get(3), 1);
        assert_eq!(m.get(2), 0);
    }

    #[test]
    fn patterns_match_the_whole_word() {
        let p = Pattern::Seq(vec![
            Pattern::Atom("create_process".into()),
            Pattern::Star(Box::new(Pattern::Any)),
            Pattern::Atom("connect".into()),
        ]);
        assert!(p.matches(&["create_process", "connect"]));
        assert!(p.matches(&["create_process", "open_key", "connect"]));
        assert!(!p.matches(&["connect"]));
        assert!(!p.matches(&["create_process", "connect", "extra"]));

        assert!(Pattern::Star(Box::new(Pattern::Any)).matches(&[]));
        assert!(!Pattern::Any.matches(&[]));
        assert!(!Pattern::Atom("a".into()).matches(&["b"]));
        let alt = Pattern::Alt(vec![Pattern::Atom("a".into()), Pattern::Atom("b".into())]);
        assert!(alt.matches(&["b"]));
        assert!(!alt.matches(&["a", "b"]));
    }
}
