[package]
name = "client"
description = "Chaos endpoint agent: collects telemetry and runs the detection pipeline."
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mimalloc.workspace = true
model.workspace = true
pipeline.workspace = true

chrono.workspace = true

[target.'cfg(windows)'.dependencies]
etw.workspace = true
