[package]
name = "client"
description = "Chaos endpoint agent: collects telemetry, detects locally, and ships to the server."
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mimalloc.workspace = true
model.workspace = true
pipeline.workspace = true
ports.workspace = true
protocol.workspace = true
transport.workspace = true

chrono.workspace = true

[target.'cfg(windows)'.dependencies]
etw.workspace = true
respond.workspace = true
